services:
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    command: /bin/bash -c "python run.py"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./:/code"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.6
    container_name: db
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
